# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django_paranoiabot.models
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('gm', models.BooleanField(default=False)),
                ('clearance', enumfields.fields.EnumField(enum=django_paranoiabot.models.Clearance, max_length=1)),
                ('home_sector', models.CharField(max_length=3)),
                ('clone_number', models.IntegerField(default=0)),
                ('custom_player_name', models.CharField(max_length=50)),
                ('pp', models.IntegerField(default=25)),
            ],
        ),
    ]
