# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_paranoiabot', '0003_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
