# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_paranoiabot', '0006_auto_20170601_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='snippet_key',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='snippet_value',
            new_name='value',
        ),
    ]
