# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_paranoiabot', '0007_auto_20170601_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='added_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='snippet',
            name='added_via',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
