# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_paranoiabot', '0008_auto_20170601_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='clone_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='telegram_id',
            field=models.IntegerField(),
        ),
    ]
