# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_paranoiabot', '0009_auto_20170603_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
