# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_paranoiabot', '0010_player_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='credits',
            field=models.IntegerField(default=1000),
        ),
    ]
